---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
indexes:
  category: "categories"
baseurl: "http://charlesbreton.github.io/"
title: "charlesbreton.github.io"
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
...
