# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Charles Breton
tagline:          
description:      SSHRC Postdoctoral Fellow <br />Department of Political Science <br />Vanderbilt University
url:            
baseurl:          

author:
  name:           'Charles Breton'
  url:            https://twitter.com/charlesbreton

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
